### ISSUE TITLE
Inclusion of Talaia in the website 

### ISSUE THREAD

**Issue by vcarela** [torsec/shield-h2020#2]
Given that Talaia is now formally a member of the SHIELD project consortium we would like to know what it is necessary to include us in the consortium page of the website (https://torsec.github.io/shield-h2020/about/consortium.html)

**Comment by mrcdb** [comment]
We just need the logo (in high quality format, best if PNG) and the description of the partner, comprising roles in the project and reference contacts.

**Comment by mrcdb** [comment]
The partner information has been added to the project website.
